//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMC_MS
{
    using System;
    using System.Collections.Generic;
    
    public partial class broadcastmsg
    {
        public broadcastmsg()
        {
            this.msgreceiver = new HashSet<msgreceiver>();
        }
    
        public int msgID { get; set; }
        public string senderID { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> saveDate { get; set; }
        public System.DateTime deliveryDate { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual ICollection<msgreceiver> msgreceiver { get; set; }
    }
}
