//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMC_MS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class slmc : DbContext
    {
        public slmc()
            : base("name=slmc")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<broadcastmsg> broadcastmsg { get; set; }
        public DbSet<city> city { get; set; }
        public DbSet<despatchnote> despatchnote { get; set; }
        public DbSet<goodsreceiveitem> goodsreceiveitem { get; set; }
        public DbSet<goodsreceivenote> goodsreceivenote { get; set; }
        public DbSet<invoice> invoice { get; set; }
        public DbSet<item> item { get; set; }
        public DbSet<itemprice> itemprice { get; set; }
        public DbSet<msgreceiver> msgreceiver { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<orderitem> orderitem { get; set; }
        public DbSet<orderstatus> orderstatus { get; set; }
        public DbSet<province> province { get; set; }
        public DbSet<replenishitem> replenishitem { get; set; }
        public DbSet<replenishment> replenishment { get; set; }
        public DbSet<reserveditem> reserveditem { get; set; }
        public DbSet<staff> staff { get; set; }
        public DbSet<staffposition> staffposition { get; set; }
        public DbSet<supplier> supplier { get; set; }
        public DbSet<target> target { get; set; }
        public DbSet<team> team { get; set; }
        public DbSet<user> user { get; set; }
    }
}
