//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMC_MS
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.invoice = new HashSet<invoice>();
            this.orderitem = new HashSet<orderitem>();
        }
    
        public int orderID { get; set; }
        public string dealerID { get; set; }
        public System.DateTime expDeliverTime { get; set; }
        public string statusID { get; set; }
        public string invName { get; set; }
        public string invAddress { get; set; }
        public string deliveryAddress { get; set; }
        public string cityID { get; set; }
        public System.DateTime orderDate { get; set; }
        public double weight { get; set; }
        public Nullable<int> despatchID { get; set; }
    
        public virtual city city { get; set; }
        public virtual despatchnote despatchnote { get; set; }
        public virtual ICollection<invoice> invoice { get; set; }
        public virtual staff staff { get; set; }
        public virtual orderstatus orderstatus { get; set; }
        public virtual ICollection<orderitem> orderitem { get; set; }
    }
}
