//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMC_MS
{
    using System;
    using System.Collections.Generic;
    
    public partial class province
    {
        public province()
        {
            this.city = new HashSet<city>();
            this.despatchnote = new HashSet<despatchnote>();
        }
    
        public string provinceID { get; set; }
        public string province1 { get; set; }
        public string province_ch { get; set; }
    
        public virtual ICollection<city> city { get; set; }
        public virtual ICollection<despatchnote> despatchnote { get; set; }
    }
}
