//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMC_MS
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.broadcastmsg = new HashSet<broadcastmsg>();
            this.despatchnote = new HashSet<despatchnote>();
            this.despatchnote1 = new HashSet<despatchnote>();
            this.msgreceiver = new HashSet<msgreceiver>();
            this.order = new HashSet<order>();
            this.reserveditem = new HashSet<reserveditem>();
            this.team1 = new HashSet<team>();
            this.user = new HashSet<user>();
        }
    
        public string staffID { get; set; }
        public string name { get; set; }
        public string name_ch { get; set; }
        public string positionID { get; set; }
        public string teamID { get; set; }
        public string address { get; set; }
        public string cityID { get; set; }
    
        public virtual ICollection<broadcastmsg> broadcastmsg { get; set; }
        public virtual city city { get; set; }
        public virtual ICollection<despatchnote> despatchnote { get; set; }
        public virtual ICollection<despatchnote> despatchnote1 { get; set; }
        public virtual ICollection<msgreceiver> msgreceiver { get; set; }
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<reserveditem> reserveditem { get; set; }
        public virtual staffposition staffposition { get; set; }
        public virtual team team { get; set; }
        public virtual ICollection<team> team1 { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
